### ISSUE TITLE
[WIP] Configuration changes: TODO list

### ISSUE THREAD

**Issue by ZyX-I** [powerline/powerline#922]
This is a TODO list from #784:
- [x] #770: Colorscheme hierarhy.
- [x] #770: Group aliasing.
- [x] #770: Port colorschemes.
- [x] #770: Test new functionality.
- [x] #770: Update documentation.
- [x] #770: Support powerline-lint.
- [ ] #3: Add basic groups.
- [x] #418: Configuration merging.
- [x] #418: Test new functionality.
- [x] #418: Update documentation.
- [x] #418: Support powerline-lint.
- [x] #783: Themes hierarchy.
- [x] #783: Port themes.
- [x] #783: Create `unicode` theme.
- [x] #783: Create `ascii` theme.
- [x] #783: Test new functionality.
- [x] #783: Update documentation.
- [x] #783: Support powerline-lint.

Done: #921 for #770, #923 for #418, #958 for #783.
